name: Posts CI

on:
  push:
    paths:
      - 'posts/**'
      - 'proto/posts/**'
      - '.github/workflows/posts.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./posts
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up Just
      uses: extractions/setup-just@v3

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image
      run: just build

    - name: Generate proto
      run: just proto

    - name: Ruff checks
      run: just check

    - name: Test
      run: just test

    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      with:
        coverageFile: posts/coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
         images: ghcr.io/${{ github.repository_owner }}/blog-posts
         tags: |
           type=ref,event=branch
           type=ref,event=tag
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}
           type=semver,pattern={{major}}
           type=sha,format=short
           type=raw,value=latest,enable={{is_default_branch}}
         labels: |
           org.opencontainers.image.source=https://github.com/jaketerrito/blog/posts
           org.opencontainers.image.url=https://github.com/jaketerrito/blog/posts

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: posts
        target: production
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
